
version: '2'
services:
  palaemon-situm-api-manager:
    image:  endimion13/situm-api-manager:0.0.1
    environment:
      - API_EMAIL=triantafyllou.ni@gmail.com
      - API_KEY=13811b07ad65c2dbaefeec038f06ca657146a1d802848eb6e0af651074b90325
      - ACCESS_TOKEN_URI=https://dashboard.situm.com/api/v1/auth/access_tokens
      - REAL_TIME_URI=https://dashboard.situm.com/api/v1/realtime/building/
      - BUILDINGS_URI=https://dashboard.situm.com/api/v1/buildings
      - GEOFENCES_URI=https://dashboard.situm.com//api/v1/geofences/search
      - DBPROXY_CLIENT_ID=palaemonRegistration
      - DBPROXY_CLIENT_SECRET=bdbbb8d5-3ee7-4907-b95c-2baae17bd10f
      - DBPROXY_OAUTH_URI=https://dss1.aegean.gr/auth/realms/palaemon/protocol/openid-connect/token
      - DBPROXY_URI=http://localhost:8090/
      - LOCATION_SERVICE_URL=http://dss.aegean.gr:7011/
    ports:
      - 8081:8083

